Repository alielsokary/GithubSearch, pull requests merged in 2021-07, with the labels that each got.

#1 feat: Introduce R.swift to the project
  .swiftlint.yml
  GithubSearch.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  R.generated.swift
Labels: size/L

#2 Add a Codacy badge to README.md
  README.md
Labels: size/XS

#3 feat: add activity indicator
  Podfile
  Podfile.lock
Labels: size/XS

#4 feat: Introduce RxSwift
  .swiftlint.yml
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/AppDelegate.swift
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/APIError.swift
  GithubSearch/Networking/GithubRouter.swift
  Podfile
  Podfile.lock
Labels: size/L

#5 feat: Configure GithubService
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/APIError.swift
  GithubSearch/Networking/GithubRouter.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/ViewController.swift
Labels: size/L

#7 chore: merge working search feature and network layer
  .gitignore
  .swiftlint.yml
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GithubSearch.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GithubSearch.xcworkspace/contents.xcworkspacedata
  GithubSearch.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GithubSearch/App/AppDelegate.swift
  GithubSearch/Info.plist
  GithubSearch/Library/Extensions/UIImageView+Extension.swift
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/APIError.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.xib
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  GithubSearch/Storyboards/Base.lproj/Main.storyboard
  GithubSearch/Support Files/Assets.xcassets/AccentColor.colorset/Contents.json
  GithubSearch/Support Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  GithubSearch/Support Files/Assets.xcassets/Contents.json
  GithubSearch/Support Files/Base.lproj/LaunchScreen.storyboard
  GithubSearchTests/GithubSearchTests.swift
  GithubSearchTests/Info.plist
  GithubSearchUITests/GithubSearchUITests.swift
  GithubSearchUITests/Info.plist
  Podfile
  Podfile.lock
  R.generated.swift
  README.md
Labels: size/XXL

#8 feat: Update Repository Model
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/Library/Extensions/String+Extension.swift
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Repo Details/View Model/RepoDetailsViewModel.swift
  GithubSearch/Scenes/Repo Details/View/RepoDetailsViewController.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.xib
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  GithubSearch/Storyboards/Base.lproj/Main.storyboard
Labels: size/L

#9 chore: merge updated model data
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/Library/Extensions/String+Extension.swift
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Repo Details/View Model/RepoDetailsViewModel.swift
  GithubSearch/Scenes/Repo Details/View/RepoDetailsViewController.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.xib
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  GithubSearch/Storyboards/Base.lproj/Main.storyboard
Labels: size/L

#10 fix: decoding error crash
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  Podfile
  Podfile.lock
  R.generated.swift
Labels: size/L

#11 refactor: SearchViewController
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/Library/Extensions/UIViewController+Extensions.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Search/View Model/RepoSearchViewModel.swift
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  Podfile
  Podfile.lock
Labels: size/L

#12 feat: Implement app coordinator
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/App/AppCoordinator.swift
  GithubSearch/App/AppDelegate.swift
  GithubSearch/Info.plist
  GithubSearch/Library/Navigation/BaseCoordinator.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Repo Details/Coordinator/RepoDetailsCoordinator.swift
  GithubSearch/Scenes/Repo Details/View Model/RepoDetailsViewModel.swift
  GithubSearch/Scenes/Repo Details/View/RepoDetailsViewController.swift
  GithubSearch/Scenes/Search/Coordinator/SearchCoordinator.swift
  GithubSearch/Scenes/Search/View Model/RepoSearchViewModel.swift
  GithubSearch/Scenes/Search/View Model/RepoViewModel.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.swift
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  GithubSearch/Storyboards/Base.lproj/Main.storyboard
Labels: size/L

#13 refactor: Merge app coordinator setup and proper dependency Injection
  GithubSearch.xcodeproj/project.pbxproj
  GithubSearch/App/AppCoordinator.swift
  GithubSearch/App/AppDelegate.swift
  GithubSearch/Info.plist
  GithubSearch/Library/Extensions/UIViewController+Extensions.swift
  GithubSearch/Library/Navigation/BaseCoordinator.swift
  GithubSearch/Model/Repositories.swift
  GithubSearch/Model/Repository.swift
  GithubSearch/Networking/GithubService.swift
  GithubSearch/Scenes/Repo Details/Coordinator/RepoDetailsCoordinator.swift
  GithubSearch/Scenes/Repo Details/View Model/RepoDetailsViewModel.swift
  GithubSearch/Scenes/Repo Details/View/RepoDetailsViewController.swift
  GithubSearch/Scenes/Search/Coordinator/SearchCoordinator.swift
  GithubSearch/Scenes/Search/View Model/RepoSearchViewModel.swift
  GithubSearch/Scenes/Search/View Model/RepoViewModel.swift
  GithubSearch/Scenes/Search/View/Cell/RepoTableViewCell.swift
  GithubSearch/Scenes/Search/View/SearchViewController.swift
  GithubSearch/Storyboards/Base.lproj/Main.storyboard
  Podfile
  Podfile.lock
  R.generated.swift
Labels: size/XL

#14 feat: Update Readme
  README.md
Labels: size/M
